name: Build, Test, Publish Docker Image

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: passwork-cli:test
          outputs: type=docker

      - name: Tests
        run: |
          docker run --rm passwork-cli:test --help

      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REPO_USERNAME }}
          password: ${{ secrets.REPO_PASSWORD }}

      - name: Push
        run: |
          docker tag passwork-cli:test ${{ secrets.REPO_USERNAME }}/passwork-cli:latest
          docker tag passwork-cli:test ${{ secrets.REPO_USERNAME }}/passwork-cli:${{ github.ref_name }}
          docker push ${{ secrets.REPO_USERNAME }}/passwork-cli:latest
          docker push ${{ secrets.REPO_USERNAME }}/passwork-cli:${{ github.ref_name }}
